### ISSUE TITLE
🥚 Initialising state

### ISSUE THREAD

**Issue by astroash** [lucyewright/tamagotchi#4]
https://github.com/lucyewright/tamagotchi/blob/a1c2abd4eb9e3c389fcb7b830ea37a46864cc9fe/src/components/App/App.js#L7-L9

Double check how you should initialise state:
https://reactjs.org/docs/react-component.html

**Comment by oliverjam** [comment]
Unless I'm missing something using a class property to initialise state is fine. We set up the curriculum using `transform-class-properties` to simplify learning classes as the constructor is kind of confusing

**Comment by astroash** [comment]
@oliverjam I think this is a typo as they’re not accessing state on the `this` object

**Comment by oliverjam** [comment]
Class properties don't need a `this` (see [the example in the TC39 proposal](https://github.com/tc39/proposal-class-fields#field-declarations))

This is how we taught initialising state: https://github.com/oliverjam/intro-react-workshop/tree/master/03-surpass-with-class#creating-state

**Comment by astroash** [comment]
Oops, my mistake. I learnt something new too 😊
